
# SEO settings
#title: "<span style='color:red'>Graph</span>"
title: "Graph*"
title2: "space" # default: ""
description: "Working with connected data and Neo4j graph databases."
keywords: "Neo4j, neo4j, graph, graph database, data import, data conversion, graphspace, semantic databases, connected data"
url: http://rajfal.github.io/ # site url
baseurl: "" # apply repo nameif use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "hnbloggithub"
twitter_username: "RafalJacyna"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Rafał"
  job      : "Graph Data Engineer"
  bio      : "I am an explorer of semantic graph databases where Connected is more meaningful than Related ..."
  thumb    : /images/author.jpg
  #email    : hnrird@gmail.com
  url      : http://rajfal.github.io
  github   : http://github.com/rajfal
  #twitter  : http://twitter.com/HeiswayiNrird
  #facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/rafaljacyna

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@RafalJacyna"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
